apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: donation-app
  labels:
    app: donation-app
data:
  NODE_ENV: "production"
  RABBITMQ_DEFAULT_USER: "guest"
  RABBITMQ_DEFAULT_PASS: "guest"
